services:
    noetic_workspace:
        image: noetic_ros_workspace 
        build:
            context: ..
            dockerfile: docker/ros_workspace.Dockerfile
        tty: true # Prevent immediate exit when running with dev containers
        volumes:
            - ../lrr_demos:/little_red_rover_ws/src/lrr_demos
            - ../lrr_base:/little_red_rover_ws/src/lrr_base
            - ../lrr_control:/little_red_rover_ws/src/lrr_control
            - ../lrr_description:/little_red_rover_ws/src/lrr_description
            - ../lrr_viz:/little_red_rover_ws/src/lrr_viz
            - ../tools:/tools
        ports:
            - "8001:8001" # agent -> rover
            - "8765:8765" # foxglove bridge
